require 'bigdecimal'
require_relative "../lib/input"
require_relative "../lib/basic_tax"
require_relative "../lib/print"
require_relative "../model/item_cart"
require_relative "../model/cart"
require_relative "../model/product"
require_relative "../model/category"
require_relative "../service/cart_calculator"
